language: node_js
node_js:
  - "11"

deploy:
  provider: heroku
  api_key:
    secure: g6Wp51qR4eEh3qEmgutXtND/F/d18pFEGdXKrJKUI99YBcZXyxEnnA+MJVUTRBzgHL9FhAz4nJS0ELQY7atEpCaSR0WdIrAayc5Z/9oL3HYo6uxCtUdMcLQoWdZTEFuFFR4wU9QZ4F/41pOQcvwr97aulDjLXVXwx6Qxch5rHGx9rJEGqx9RiVEuXhi6A0Z/798PofDjdQcLdfNIWjuJ2b4nAiQdCL5s0mGQc7kn4F2wTYNgT2EX14oITpA7Rjakf1rlSdtgqJYbdcrazds7PlrZEZUUcn+q1siFvmAgNEPKW43uzNrD/NSBIJ6lmEz1xz+wb363KM5YdQkSRHxyerPxtiKhR1HNd8GXM1PqQP/8JduOAtUkMAMH6dYWC+gmPvqkErh3StlVmnnKPbGENKDw4yB7GyuDuTxUW3jwwVB9bmOwikRAVC3/QZTDToS04sYlbs9elL9/0oWGCpfxEPozMGzWyP4uBMSaeYnM/zDNTw/C8QAwWbqTNzlTqOebjkpTdQj6EQrSLRInFbJdGo1cuEyVu7nftGBJgWeoT+qLLOShUT9zNR42vU8SI4uIv3aJKRV5bN5MRA9LAM3Vl1oCyRp9/vsbCI69rWWSRaFTmD/v6J9eN+3Tf2Jklux80gYTBWJdwZOucUYqPoISBO8dPXXtSbasftw9qRsS5dQ=
  app: bms-back
  on:
    repo: lordpuma/BMS-backend
